version: "3.7"

networks:
  backend:

services:
  &db mysql:
    hostname: *db
    container_name: *db
    restart: unless-stopped
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - backend
    volumes:
      - ./db-data:/var/lib/mysql
      
  &phpmyadmin phpmyadmin:
    hostname: *phpmyadmin
    container_name: *phpmyadmin
    restart: unless-stopped
    image: phpmyadmin:latest
    environment:
      PMA_HOST: *db
      MYSQL_HOST: *db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    networks:
      - backend
    depends_on:
      - *db

  &cache redis:
    container_name: *cache
    hostname: *cache
    restart: unless-stopped
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - backend

  &backend php:
    hostname: *backend
    container_name: *backend
    restart: unless-stopped
    build: ./server
    networks:
      - backend
    environment:
      FPM_PORT: ${PHP_FPM_PORT}
      FPM_USER: ${PHP_FPM_USER_ID}
      CURRENT_USER: ${PHP_FPM_USER}
      FPM_GROUP: ${PHP_FPM_GROUP}
    volumes:
      - ./server:/var/www/lar-react
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
    depends_on: 
      - *db
      - *cache

  &web-server nginx:
    container_name: *web-server
    hostname: *web-server
    restart: unless-stopped
    image: nginx:1.19
    ports:
      - ${NGINX_PORT}:80
    networks:
      - backend
    volumes:
      - ./server:/var/www/lar-react/
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on: 
      - *backend